# Generated by Django 2.1.7 on 2019-03-10 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataDate', models.DateField(blank=True, null=True)),
                ('Detail', models.TextField(help_text='Enter a brief description of the room', max_length=1000)),
                ('UnitUsed', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataType', models.CharField(help_text='enter your Data Type', max_length=200)),
                ('DataTypeDetail', models.TextField(help_text='Enter a brief description of the data Type', max_length=1000)),
                ('Rate', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomId', models.UUIDField(default=uuid.uuid4, help_text='Unique room id', primary_key=True, serialize=False)),
                ('RoomNumber', models.CharField(help_text='enter your room number here', max_length=200)),
                ('RoomDetail', models.TextField(help_text='Enter a brief description of the room', max_length=1000)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'Occupied'), ('a', 'Available')], default='a', help_text='Room Status', max_length=1)),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='DataType',
            field=models.ManyToManyField(help_text='Select a type for this data', to='homedetail.DataType'),
        ),
        migrations.AddField(
            model_name='data',
            name='RoomId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homedetail.Room'),
        ),
    ]
