# Generated by Django 2.1.7 on 2019-03-10 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homedetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatype',
            old_name='DataType',
            new_name='DataType_Name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='UserID',
        ),
        migrations.AddField(
            model_name='room',
            name='UserID',
            field=models.ManyToManyField(help_text='user in the room', to=settings.AUTH_USER_MODEL),
        ),
    ]
