# Generated by Django 2.1.7 on 2019-03-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0002_auto_20190310_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='DataType',
            new_name='Data_Type',
        ),
    ]
