# Generated by Django 2.1.7 on 2019-03-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0003_auto_20190310_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Data_Type',
        ),
        migrations.AddField(
            model_name='data',
            name='Data_Type',
            field=models.ForeignKey(help_text='Select a type for this data', null=True, on_delete=django.db.models.deletion.SET_NULL, to='homedetail.DataType'),
        ),
    ]
