# Generated by Django 2.1.7 on 2019-03-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0004_auto_20190310_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['RoomNumber']},
        ),
    ]
