# Generated by Django 2.1.7 on 2019-03-15 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homedetail', '0005_auto_20190315_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='UserID',
        ),
        migrations.AddField(
            model_name='room',
            name='UserID',
            field=models.ForeignKey(help_text='user in the room', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
