# Generated by Django 2.1.7 on 2019-03-16 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0006_auto_20190315_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='UserID',
            field=models.ForeignKey(help_text='Room owner of the room', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
