# Generated by Django 2.1.7 on 2019-03-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0007_auto_20190316_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='DataDeadLine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Paid'), ('N', 'Not Paid')], default='a', help_text='Room Status', max_length=1),
        ),
        migrations.AlterField(
            model_name='data',
            name='Detail',
            field=models.TextField(help_text='Enter a brief description of the data', max_length=1000),
        ),
    ]
