# Generated by Django 2.1.7 on 2019-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0009_auto_20190316_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='UnitUsed',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='Rate',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
