# Generated by Django 2.1.7 on 2019-03-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0012_auto_20190320_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Detail',
            field=models.TextField(blank=True, help_text='Enter a brief description of the data', max_length=1000, null=True),
        ),
    ]
