# Generated by Django 2.1.7 on 2019-04-02 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homedetail', '0014_roomowner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomOwner',
            new_name='UserInTheRoom',
        ),
    ]
