# Generated by Django 2.1.7 on 2019-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0017_auto_20190407_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintheroom',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Owner'), ('T', 'Tenant')], default='T', help_text='User Status', max_length=1),
        ),
    ]
