# Generated by Django 2.0.13 on 2019-04-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0018_auto_20190415_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='status',
        ),
    ]
