# Generated by Django 2.0.13 on 2019-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0020_auto_20190416_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Paid'), ('O', 'On Process'), ('N', 'Not Paid')], default='N', help_text='Room Status', max_length=1),
        ),
    ]
