# Generated by Django 2.1.7 on 2019-03-19 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homedetail', '0011_auto_20190316_2138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_date', models.DateField(blank=True, null=True)),
                ('Sub_Total', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('Evidence', models.ImageField(null=True, upload_to='evidences/')),
                ('status', models.CharField(blank=True, choices=[('c', 'complete'), ('i', 'incomplete'), ('p', 'Processing')], default='p', help_text='Payment status', max_length=1)),
                ('PayerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('Total', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('Data', models.ForeignKey(help_text='order Data', null=True, on_delete=django.db.models.deletion.SET_NULL, to='homedetail.Data')),
                ('Invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payment.Invoice')),
                ('Rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homedetail.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentTypeDetail', models.TextField(help_text='Detail of the payment method', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='Payment_method',
            field=models.ManyToManyField(help_text='Select a method for this payment', to='payment.PaymentType'),
        ),
    ]
