# Generated by Django 2.1.7 on 2019-03-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'complete'), ('i', 'incomplete'), ('p', 'Processing')], default='i', help_text='Payment status', max_length=1),
        ),
    ]
