# Generated by Django 2.1.7 on 2019-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190319_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
