# Generated by Django 2.1.7 on 2019-03-20 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0011_auto_20190316_2138'),
        ('payment', '0003_auto_20190319_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='RoomId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homedetail.Room'),
        ),
    ]
