# Generated by Django 2.1.7 on 2019-03-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_invoice_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='PaymentTypeDetail',
            field=models.CharField(help_text='Detail of the payment method', max_length=1000),
        ),
    ]
