# Generated by Django 2.1.7 on 2019-04-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0015_auto_20190402_2257'),
        ('payment', '0005_auto_20190320_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='Data',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='Rate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='Sub_Total',
            new_name='Total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RoomId',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Data',
            field=models.ForeignKey(help_text='order Data', null=True, on_delete=django.db.models.deletion.SET_NULL, to='homedetail.Data'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homedetail.DataType'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
