# Generated by Django 2.1.7 on 2019-04-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20190406_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Total',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'complete'), ('F', 'Fail'), ('P', 'Processing')], default='i', help_text='Payment status', max_length=1),
        ),
    ]
