# Generated by Django 2.0.13 on 2019-04-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Payment_method',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Payment_method',
            field=models.ForeignKey(help_text='Select a method for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.PaymentType'),
        ),
    ]
