# Generated by Django 2.1.7 on 2019-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedetail', '0013_auto_20190323_2029'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNotificaiton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(help_text='Enter The Topic of the notification', max_length=200)),
                ('Detail', models.TextField(help_text='Enter a brief description of the notification', max_length=1000)),
                ('notification_type', models.CharField(blank=True, choices=[('u', 'Utility'), ('o', 'other'), ('a', 'announcement')], default='a', help_text='Room Status', max_length=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Notification',
            new_name='SpecificNotification',
        ),
    ]
